---
language: ruby
rvm:
- 1.9.3
branches:
  only:
  - develop
script: rake travis
env:
  global:
  - secure: "m6ATzo+cRfJS5FkmdNUxrGN5RmLBjKWlGdyqODs6LLufIWjCWSEm1evppQ5l\noru2e4DcwgMhWaUty5WfAoEQIGy8AnLaZQq2ExoIRHCmjYvBcyz0xE/q984d\nptFdP8uNwwBr+J90VIHgqkLc8+d0qNM3MubzPWvktt/M0LSR8zE="
