name: Coding Spaces
title: Coding Spaces
author: Isaac Christoffersen
local_tx: America/New_York
disqus: codingspaces
base_url: http://localhost:4242

asciidoctor:
  :compact: true
  :eruby: erubis
  :attributes:
    idprefix: ''
    idseparator: '-'

scss:
  :line_numbers: true
  :style: :expanded

profiles:
  development:
    disqus_developer: true
    dev: true
    deploy: 
      dummy:

  production:
    base_url: http://codingspaces.github.io
    deploy:
      host: github_pages
      branch: master
